### ISSUE TITLE
showing 0 updates

### ISSUE THREAD

**Issue by ramanveerji** [rajbos/github-fork-updater#74]
I have forked the repo to my account and on checking for updates it shows 0 update. I have forked to my account but it is showing the following text

> Running a check on all repositories inside of organization [ramanveerji] with user [xxx] and a PAT that has length [40]

Why it showing user xxx and organization, it should show user ramanveerji and not the organization.

**Comment by rajbos** [comment]
@ramanveerji , that is just how things are displayed from the input [here](https://github.com/rajbos/github-fork-updater/blob/fd90ec638153410be3cea2d34c898715f7db65d9/.github/workflows/update-workflow.yml#L40). I should clean that up a bit indeed. Thanks for notifying me!

**Comment by ramanveerji** [comment]
> @ramanveerji , that is just how things are displayed from the input [here](https://github.com/rajbos/github-fork-updater/blob/fd90ec638153410be3cea2d34c898715f7db65d9/.github/workflows/update-workflow.yml#L40). I should clean that up a bit indeed. Thanks for notifying me! 

Yes please. I hope after you cleanup things and fix it up, it should work with the user also and not with organization.

**Comment by ramanveerji** [comment]
I am always getting this error, kindly check.

Running a check on all repositories inside of organization [] with user [ramanveerji] and a PAT that has length [40]
Error calling api at [https://api.github.com/orgs//repos?per_page=100]:
  StatusCode: NotFound
  RateLimit-Limit: [12](https://github.com/ramanveerji/github-fork-updater/actions/runs/6435803405/job/17477823278#step:5:13)500
  RateLimit-Remaining: 12494
  RateLimit-Reset: [16](https://github.com/ramanveerji/github-fork-updater/actions/runs/6435803405/job/17477823278#step:5:17)96622085
  RateLimit-Used: 6
{"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
WARNING: Call to GitHub Api [https://api.github.com/orgs//repos?per_page=100] had [not found] result with documentation url [https://docs.github.com/rest]
Found [1] repositories in []

Skipping repository [] since it is not a fork or has been archived or is disabled
Found [0] forks with available updates



What i did extra in my repo is I have removed orgname and added ${{ github.repository_owner }} in username. I get the same results when this is changed or it is same as original. I have tried both PAT and GH App. Same error.

**Comment by rajbos** [comment]
Can you add a link to your repo / workflow run please? It seems to call into the org from the logs, but there is no org name in the call, hence the error.

Example: 
`https://api.github.com/orgs//repos?per_page=100`

Should be at least:
`https://api.github.com/orgs/<organization here>/repos?per_page=100`

So somehow it thinks it needs to run for an org, instead of a user

**Comment by ramanveerji** [comment]
> Can you add a link to your repo / workflow run please? It seems to call into the org from the logs, but there is no org name in the call, hence the error.
> 
> Example: 
> `https://api.github.com/orgs//repos?per_page=100`
> 
> Should be at least:
> `https://api.github.com/orgs/<organization here>/repos?per_page=100`
> 
> So somehow it thinks it needs to run for an org, instead of a user


https://github.com/ramanveerji/github-fork-updater/actions/runs/6435832333/job/17477920868#step:5:1

**Comment by ramanveerji** [comment]
@rajbos Please fix the issue, I really like your implementation of updating forks. I want to use it.

**Comment by rajbos** [comment]
@ramanveerji : I've found an issue with the error message I was looking at to change from Org to User repos. That has been corrected. Please update your fork with my latest changes and rerun the workflow. Let me know if it works!

**Comment by ramanveerji** [comment]
> @ramanveerji : I've found an issue with the error message I was looking at to change from Org to User repos. That has been corrected. Please update your fork with my latest changes and rerun the workflow. Let me know if it works!

Now it is showing the updates, but still not showing all fork updates. Also after applying update-fork label, I am getting an error, please check [this](https://github.com/ramanveerji/github-fork-updater/actions/runs/6529126428/job/17726321402#step:6:92)

**Comment by rajbos** [comment]
I see `Resource not accessible by integration` in the logs on the calls to for example: `Error calling api at [https://api.github.com/repos/ramanveerji/github-fork-updater/issues/18/comments]`. 

Please check the scopes for the GitHub App you are using. Seems like the scope for `issues:write` is missing.

**Comment by ramanveerji** [comment]
> I see `Resource not accessible by integration` in the logs on the calls to for example: `Error calling api at [https://api.github.com/repos/ramanveerji/github-fork-updater/issues/18/comments]`.
> 
> Please check the scopes for the GitHub App you are using. Seems like the scope for `issues:write` is missing.

For issues, I have given Read and Write.
For actions, contents, deployments, metadeta Read Only is given.

**Comment by rajbos** [comment]
For `actions` and `contents`, write access is needed as well

**Comment by ramanveerji** [comment]
> For `actions` and `contents`, write access is needed as well

I created the app again and finally now I can update with the label.

**Comment by ramanveerji** [comment]
But I think it is still not checking all the forks in my account. I have checked manually and found that many forks need the update but those are not visible in the issues tab.

**Comment by ramanveerji** [comment]
It found only 30 repositories. https://github.com/ramanveerji/github-fork-updater/actions/runs/6536559621/job/17748531586#step:5:26

This is the issue. It should find all repos. Please suggest how to fix this.

**Comment by rajbos** [comment]
Seems like I never implemented pagination support for the load repos calls 😄.

I already have that code [here](https://github.com/rajbos/actions-marketplace-checks/blob/main/.github/workflows/library.ps1#L75-L103), so I need to find some time to implement it in this repo as well.

**Comment by ramanveerji** [comment]
> Seems like I never implemented pagination support for the load repos calls 😄.
> 
> I already have that code [here](https://github.com/rajbos/actions-marketplace-checks/blob/main/.github/workflows/library.ps1#L75-L103), so I need to find some time to implement it in this repo as well.

Please please do implement. That would be very helpful.

**Comment by ramanveerji** [comment]
> Seems like I never implemented pagination support for the load repos calls 😄.
> 
> I already have that code [here](https://github.com/rajbos/actions-marketplace-checks/blob/main/.github/workflows/library.ps1#L75-L103), so I need to find some time to implement it in this repo as well.

I tried to add that code but I think I was not able to add it properly. Can you tell where to add that code and in which file? 

Check [this](https://github.com/ramanveerji/github-fork-updater/blob/main/github-calls.ps1).

**Comment by rajbos** [comment]
Thanks for taking the time to try to fix this.
The changes you have look good. What is the error message from this (assuming that it throws an exception?).

**Comment by ramanveerji** [comment]
> Thanks for taking the time to try to fix this.
> The changes you have look good. What is the error message from this (assuming that it throws an exception?).

It is still not checking all pages.
Check the [logs](https://github.com/ramanveerji/github-fork-updater/actions/runs/6753711548/job/18360473345#step:5:1).

**Comment by ramanveerji** [comment]
Please sir have a look and fix this repo please. This repo would help many people.

**Comment by rajbos** [comment]
I have added the pagination to the calls @ramanveerji . Please update the fork and test again.

**Comment by ramanveerji** [comment]
> I have added the pagination to the calls @ramanveerji . Please update the fork and test again.

Thanks for pushing the update. I updated the fork and I think I have received all the updates for my forks. Thanks a lot for fixing this. I have one doubt. I got 131 updates for my forks, is it safe to run so many workflow actions of checking and reporting the issues?

**Comment by rajbos** [comment]
Awesome! I'll close this issue then.

It's only one workflow that does the run and checks all the repos, and the only thing it does is create an issue. I see no issues with that.

**Comment by ramanveerji** [comment]
> Awesome! I'll close this issue then.
> 
> It's only one workflow that does the run and checks all the repos, and the only thing it does is create an issue. I see no issues with that.

Thanks a lot. I highly appreciate your work.
